### ISSUE TITLE
usage_dict or pokemon_dict Nonetyping

### ISSUE THREAD

**Issue by WilliamCoffeyTri** [jeffreyscheng/Dialgarithm#3]
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    setup_with_user_input()
  File "/root/Documents/Mewtagen/dialgarithm/dialgarithm.py", line 15, in setup_with_user_input
    UsageReader.clean_up_usage()
  File "/root/Documents/Mewtagen/dialgarithm/usage_reader.py", line 104, in clean_up_usage
    other_mons = [mon for mon in Model.dex.pokemon_dict.keys() if mon not in Model.usage_dict.keys()]
  File "/root/Documents/Mewtagen/dialgarithm/usage_reader.py", line 104, in <listcomp>
    other_mons = [mon for mon in Model.dex.pokemon_dict.keys() if mon not in Model.usage_dict.keys()]
AttributeError: 'NoneType' object has no attribute 'keys'

This crash occurs directly after selecting any tier. If the tier has not been selected before, it will write DEX.txt prior to crashing.

**Comment by jeffreyscheng** [comment]
I think I deployed a hotfix for this (the issue was because the usage stats updated this morning).  Did you clone the most recent commit?
