### ISSUE TITLE
Syntax Error under line 50 of run.py

### ISSUE THREAD

**Issue by JoshuaHowe99** [jeffreyscheng/Dialgarithm#4]
C:\Users\tgif2\Desktop\Mewtagen>python run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from dialgarithm.dialgarithm import *
  File "C:\Users\tgif2\Desktop\Mewtagen\dialgarithm\dialgarithm.py", line 50
    [print(team) for team in Evolve.output]
         ^
SyntaxError: invalid syntax

I'm sorry if this is super simple, I am in new territory. Thanks!

**Comment by jeffreyscheng** [comment]
Hi, I think this is a python 2 vs. python 3 error?  Try "python3 run.py" and let me know if it still doesn't work!

**Comment by JoshuaHowe99** [comment]
Well, you were correct. Changing to Python 3 fixed that problem... only for me to run into another.

C:\Users\tgif2\Desktop\Mewtagen>python run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from dialgarithm.dialgarithm import *
  File "C:\Users\tgif2\Desktop\Mewtagen\dialgarithm\dialgarithm.py", line 2, in <module>
    from .usage_reader import *
  File "C:\Users\tgif2\Desktop\Mewtagen\dialgarithm\usage_reader.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

There could just be something obvious I am missing.

**Comment by the-ashh** [comment]
do `pip3 install requests`
pip3 is how you install modules in python3. there will be more modules that you might have to install.

**Comment by JoshuaHowe99** [comment]
I think I got it working! Thanks to both of you!
