### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by cstew527** [jeffreyscheng/Dialgarithm#5]
When I run the program, I get an error that says
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\X\Downloads\Mewtagen-master (1)\Mewtagen-master>py -3 run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from dialgarithm.dialgarithm import *
  File "C:\Users\X\Downloads\Mewtagen-master (1)\Mewtagen-master\dialg
arithm\dialgarithm.py", line 2, in <module>
    from .usage_reader import *
  File "C:\Users\X\Downloads\Mewtagen-master (1)\Mewtagen-master\dialg
arithm\usage_reader.py", line 2, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

I'm not sure how to fix it.

**Comment by jeffreyscheng** [comment]
Install the module with pip!  You'll likely have to install many other packages as well.

**Comment by cstew527** [comment]
Hey, this time i got an Attribute Error

Traceback (most recent call last):
  File "run.py", line 5, in <module>
    setup_with_user_input()
  File "C:\Users\X\Downloads\Mewtagen-master (1)\Mewtagen-master\dialg
arithm\dialgarithm.py", line 16, in setup_with_user_input
    MovesetFactory().get_movesets()
  File "C:\Users\X\Downloads\Mewtagen-master (1)\Mewtagen-master\dialg
arithm\moveset_factory.py", line 45, in get_movesets
    for pokemon in list_of_pokemon}
  File "C:\Users\X\Downloads\Mewtagen-master (1)\Mewtagen-master\dialg
arithm\moveset_factory.py", line 45, in <dictcomp>
    for pokemon in list_of_pokemon}
  File "C:\Users\X\Downloads\Mewtagen-master (1)\Mewtagen-master\dialg
arithm\moveset_factory.py", line 18, in read_pokemon
    pokemon_string = soup.script.contents[0]
AttributeError: 'NoneType' object has no attribute 'contents'
